### ISSUE TITLE
AttributeError: 'str' object has no attribute 'name'

### ISSUE THREAD

**Issue by cunningr** [cunningr/sdtables#1]
When trying to traverse the list of tables in a workbook we get the following traceback;

Traceback (most recent call last):
  File "/usr/local/bin/dna_workflows", line 196, in <module>
    main()
  File "/usr/local/bin/dna_workflows", line 41, in main
    schema = yaml.load(open(manifest, 'r'), Loader=yaml.SafeLoader)
FileNotFoundError: [Errno 2] No such file or directory: 'manifest.yml'
root@7d42060ec82b:/# cp /mnt/manifest.yml ./
root@7d42060ec82b:/# dna_workflows --build-xlsx example.xlsx
Traceback (most recent call last):
  File "/usr/local/bin/dna_workflows", line 196, in <module>
    main()
  File "/usr/local/bin/dna_workflows", line 44, in main
    wb = schema_tools.build_workflow_task_sheet(wb, schema)
  File "/usr/local/lib/python3.8/site-packages/dna_workflows/schema_tools.py", line 109, in build_workflow_task_sheet
    if 'workflow' == table.name:
AttributeError: 'str' object has no attribute 'name'

**Comment by cunningr** [comment]
This is due to a breaking change introduced in openpyxl in 3.0.4 (24/06/2020).  We will at some point take advantage of the new tables handling features introduced but for now we are pinning our build to version 3.0.3.

Till now the only available method for reading tables from a worksheet was the internal ```ws._tables``` method.  This now seems to have a more complete implementation.

**Comment by cunningr** [comment]
patched in sdtables 1.0.3 to use ```openpyxl==3.0.3```

**Comment by cunningr** [comment]
case closed
